# Generated by Django 3.0.1 on 2019-12-18 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassifiedSentences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=256)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classify.ClassificationChoices')),
            ],
        ),
    ]
